# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6224a1f18d25086f69d1bcb2e03d29da168fde00ad7d9a31985103e1659204cb091ac173ee45b4fa99c4c25845510a60fe754feab2dd85f81920cbb474ca31a5

test:
  secret_key_base: 46d123db67f53b17f6522ac2acf881b71bc5c9d527d5fd92d23748148d549cafebafc47fcf7a6d017d176047736f5a2ab5c519b79e6620c1a9f90a394f034efd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
